### ISSUE TITLE
replace_all_na() errors when combine with purrr::modify_at()

### ISSUE THREAD

**Issue by leungi** [nhemerson/tibbleColumns#2]
``` r
library(tidyverse)
library(tibbleColumns)
packageVersion("tibbleColumns")
#> [1] '0.2.1'

# replace_all_na() errors  
mtcars %>% 
  tbl_out("cars") %>% 
  count(cyl,vs) %>% 
  spread(cyl,n) %>% 
  sjmisc::set_na(na = 0) %>% 
  purrr::modify_at(c("8"), replace_all_na)
#> Error: Column index must be at most 1 if positive, not 2

# as.character() works
mtcars %>% 
  tbl_out("cars") %>% 
  count(cyl,vs) %>% 
  spread(cyl,n) %>% 
  sjmisc::set_na(na = 0) %>% 
  purrr::modify_at(c("8"), as.character) %>% 
  glimpse()
#> Observations: 2
#> Variables: 4
#> $ vs  <dbl> NA, 1
#> $ `4` <int> 1, 10
#> $ `6` <int> 3, 4
#> $ `8` <chr> "14", NA
```

Created on 2018-07-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nhemerson** [comment]
Thanks for this find. Looks to be an issue with latest commit. I'll get it fixed.

**Comment by nhemerson** [comment]
This bug is fixed. It was caused by adding tbl_df() within the function. When called within modify_at it was creating an out of bounds error due to the tibble::check_names_df.numeric method.

**Comment by leungi** [comment]
@nhemerson, thanks for the prompt fix!

I'm slowly adopting the workflow; great work :)

**Comment by nhemerson** [comment]
Awesome, that's great to hear!

**Comment by nhemerson** [comment]
Realized the function still needed to output a DF so I updated that with last commit. Download again for latest.

**Comment by leungi** [comment]
Noted. Thanks.
